### ISSUE TITLE
zks_api: Implement `zks_getRawBlockTransactions` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#141]
## **Description:**
Implement the [`zks_getRawBlockTransactions`](https://github.com/matter-labs/zksync-era/blob/a980ac61f484a3b6bdbe11e606977d0d92d4e9ff/core/lib/zksync_core/src/api_server/web3/backend_jsonrpc/namespaces/zks.rs#L88) method. This function returns data of transactions in a block for a given block number.

```rust
/// Retrieves data of transactions in a block by block number.
fn zks_getRawBlockTransactions(&self, block: u32) -> jsonrpc_core::BoxFuture<jsonrpc_core::Result<Vec<TransactionData>>> {
    not_implemented("zks_getRawBlockTransactions")
}
```

#### Expected response
Command:
```
curl -X POST -H "Content-Type: application/json" \
--data '{"jsonrpc": "2.0", "id": 1, "method": "zks_getRawBlockTransactions", "params": [ 5817 ]}' \
"https://mainnet.era.zksync.io"
```

Response:
```
{
  "jsonrpc": "2.0",
  "result": [
    {
      "common_data": {
        "L1": {
          "canonicalTxHash": "0x22de7debaa98758afdaee89f447ff43bab5da3de6acca7528b281cc2f1be2ee9",
          "deadlineBlock": 0,
          "ethBlock": 16751339,
          "ethHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
          "fullFee": "0x0",
          "gasLimit": "0x989680",
          "gasPerPubdataLimit": "0x320",
          "layer2TipFee": "0x0",
          "maxFeePerGas": "0x0",
          "opProcessingType": "Common",
          "priorityQueueType": "Deque",
          "refundRecipient": "0x87869cb87c4fa78ca278df358e890ff73b42a39e",
          "sender": "0x87869cb87c4fa78ca278df358e890ff73b42a39e",
          "serialId": 67,
          "toMint": "0x0"
        }
      },
      "execute": {
        "calldata": "0x471c46c800000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000100000000000000000000000031edd5a882583cbf3a712e98e100ef34ad6934b400000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001",
        "contractAddress": "0xfc5b07a5dd1b80cf271d35642f75cc0500ff1e2c",
        "factoryDeps": [],
        "value": "0x0"
      },
      "received_timestamp_ms": 1677887544169
    }
  ],
  "id": 1
}
```

### **Requirements:**

1. **Implement the Method:**
    - The method should take in a `block` of type `u32`.
    - It should return data of transactions in the specified block as a `Vec<TransactionData>`.

2. **Unit Tests:**
    - Write unit tests ensuring the `zks_getRawBlockTransactions` method functions correctly.
    - Test various edge cases, including blocks with no transactions.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `zks_getRawBlockTransactions` method.
    - Include details on parameters, return values, and any possible exceptions or errors.

### **Task Checklist:**
- [ ] Implement the `zks_getRawBlockTransactions` method.
- [ ] Write unit tests for the `zks_getRawBlockTransactions` method.
- [ ] Add inline documentation for the `zks_getRawBlockTransactions` method.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!
