### ISSUE TITLE
zks_api: Implement `zks_getAllAccountBalances` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#142]
## **Description:**
Implement the [`zks_getAllAccountBalances`](https://github.com/matter-labs/zksync-era/blob/a980ac61f484a3b6bdbe11e606977d0d92d4e9ff/core/lib/zksync_core/src/api_server/web3/backend_jsonrpc/namespaces/zks.rs#L51) method. This function returns all balances for confirmed tokens given by an account address.

```rust
/// Retrieves all balances for confirmed tokens by account address.
fn zks_getAllAccountBalances(&self, address: Address) -> jsonrpc_core::BoxFuture<jsonrpc_core::Result<HashMap<Address, U256>>> {
    not_implemented("zks_getAllAccountBalances")
}
```

#### Expected response
Command:
```
curl -X POST -H "Content-Type: application/json" \
--data '{"jsonrpc": "2.0", "id": 1, "method": "zks_getAllAccountBalances", "params": [ "0x98E9D288743839e96A8005a6B51C770Bbf7788C0" ]}' \
"https://mainnet.era.zksync.io"
```

Response:
```
{
  "jsonrpc": "2.0",
  "result": {
    "0x0000000000000000000000000000000000000000": "0x2fbd72a1121b3100"
  },
  "id": 2
}
```

### **Requirements:**

1. **Implement the Method:**
    - The method should take in an `address` of type `Address`.
    - It should return a `HashMap<Address, U256>` containing all balances for confirmed tokens for the specified address.

2. **Unit Tests:**
    - Write unit tests ensuring the `zks_getAllAccountBalances` method functions correctly.
    - Test various edge cases, including addresses with no confirmed tokens.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `zks_getAllAccountBalances` method.
    - Include details on parameters, return values, and any possible exceptions or errors.

### **Task Checklist:**
- [ ] Implement the `zks_getAllAccountBalances` method.
- [ ] Write unit tests for the `zks_getAllAccountBalances` method.
- [ ] Add inline documentation for the `zks_getAllAccountBalances` method.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!
