### ISSUE TITLE
zks_api: Implement `zks_getTokenPrice` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#145]
## **Description:**
We need to implement the [`zks_getTokenPrice`](https://github.com/matter-labs/zksync-era/blob/a980ac61f484a3b6bdbe11e606977d0d92d4e9ff/core/lib/zksync_core/src/api_server/web3/backend_jsonrpc/namespaces/zks.rs#L48) method. This function retrieves the price of a given token in USD.

```rust
/// Fetches the price of the specified token in USD.
fn zks_getTokenPrice(&self, address: Address) -> jsonrpc_core::BoxFuture<jsonrpc_core::Result<f64>> {
    not_implemented("zks_getTokenPrice")
}
```

#### Expected response
Command:
```
curl -X POST -H "Content-Type: application/json" \
--data '{"jsonrpc": "2.0", "id": 1, "method": "zks_getTokenPrice", "params": [ "0x0000000000000000000000000000000000000000" ]}' \
"https://mainnet.era.zksync.io"
```

Response:
```
{
  "jsonrpc": "2.0",
  "result": "1908.42",
  "id": 1
}
```

### **Notes:**
- The price used by the zkSync Era team may vary slightly from the current market price.
- On testnets, token prices might differ from the actual market price.

### **Requirements:**

1. **Implement the Method:**
    - The method should accept an `address` of type `Address`.
    - It should return the price of the token in USD as `f64`.

2. **Unit Tests:**
    - Write unit tests ensuring the `zks_getTokenPrice` method functions correctly.
    - Test various edge cases, including non-existent token addresses.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `zks_getTokenPrice` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

### **Task Checklist:**
- [ ] Implement the `zks_getTokenPrice` method.
- [ ] Write unit tests for the `zks_getTokenPrice` method.
- [ ] Add inline documentation for the `zks_getTokenPrice` method.

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!

**Comment by MexicanAce** [comment]
This is already implemented
