### ISSUE TITLE
zks_api: Implement `zks_getTransactionDetails` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#146]
## **Description:**
We need to implement the [`zks_getTransactionDetails`](https://github.com/matter-labs/zksync-era/blob/a980ac61f484a3b6bdbe11e606977d0d92d4e9ff/core/lib/zksync_core/src/api_server/web3/backend_jsonrpc/namespaces/zks.rs#L85) method. This function retrieves data from a specific transaction based on the provided transaction hash.

```rust
/// Fetches detailed information about the specified transaction.
fn zks_getTransactionDetails(&self, hash: H256) -> jsonrpc_core::BoxFuture<jsonrpc_core::Result<TransactionDetails>> {
    not_implemented("zks_getTransactionDetails")
}
```

#### Expected response
Command:
```
curl -X POST -H "Content-Type: application/json" \
--data '{"jsonrpc": "2.0", "id": 1, "method": "zks_getTransactionDetails", "params": [ "0x22de7debaa98758afdaee89f447ff43bab5da3de6acca7528b281cc2f1be2ee9" ]}' \
"https://mainnet.era.zksync.io"
```

Response:
```
{
  "jsonrpc": "2.0",
  "result": {
    "ethCommitTxHash": "0x3da5b6eda357189c9243c41c5a33b1b2ed0169be172705d74681a25217702772",
    "ethExecuteTxHash": "0xdaff5fd7ff91333b161de54534b4bb6a78e5325329959a0863bf0aae2b0fdcc6",
    "ethProveTxHash": "0x2f482d3ea163f5be0c2aca7819d0beb80415be1a310e845a2d726fbc4ac54c80",
    "fee": "0x0",
    "gasPerPubdata": "0x320",
    "initiatorAddress": "0x87869cb87c4fa78ca278df358e890ff73b42a39e",
    "isL1Originated": true,
    "receivedAt": "2023-03-03T23:52:24.169Z",
    "status": "verified"
  },
  "id": 1
}
```

### **Requirements:**

1. **Implement the Method:**
    - The method should accept a `hash` of type `H256`.
    - It should return detailed data about the transaction as `TransactionDetails`.

2. **Unit Tests:**
    - Write unit tests ensuring the `zks_getTransactionDetails` method functions correctly.
    - Test with different transaction hashes, including invalid or non-existent ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `zks_getTransactionDetails` method.
    - Include details about parameters, return values, and any possible exceptions or errors.

### **Task Checklist:**
- [ ] Implement the `zks_getTransactionDetails` method.
- [ ] Write unit tests for the `zks_getTransactionDetails` method.
- [ ] Add inline documentation for the `zks_getTransactionDetails` method.

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!
