### ISSUE TITLE
checklist: Implement zks_ namespace API 

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#147]
## Description 

The `zks` namespace JSON-RPC provides L2-specific details that are required for block explorer integration, debugging, and other related capabilities. The below tasks are to be implemented to successfully close this checklist. 

### Task Checklist 

- [x] https://github.com/matter-labs/era-test-node/issues/141
- [x] https://github.com/matter-labs/era-test-node/issues/142
- [x] https://github.com/matter-labs/era-test-node/issues/143
- [x] https://github.com/matter-labs/era-test-node/issues/144
- [x] https://github.com/matter-labs/era-test-node/issues/145
- [x] https://github.com/matter-labs/era-test-node/issues/146
- [x] https://github.com/matter-labs/era-test-node/issues/153

**Comment by MexicanAce** [comment]
These initial `zks_` endpoints are now completely implemented
