### ISSUE TITLE
hardhat_api: Implement `hardhat_setCode` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#149]
## **Description:**
We need to implement the [`hardhat_setCode`](https://github.com/NomicFoundation/hardhat/blob/781161c00a467a1da392d684950eec4d8574b868/packages/hardhat-network-helpers/src/helpers/setCode.ts#L13) method. This function modifies the bytecode stored at a specified account's address.

```rust
// Interface in the `trait`
#[rpc(name = "hardhat_setCode")]
fn set_code(
    &self,
    address: Address, // The address where the given code should be stored
    code: Vec<u8>, // The bytecode to store at the given address
) -> BoxFuture<Result<()>>;

// Actual code in the `impl`
fn set_code(
    &self,
    address: Address,
    code: Vec<u8>,
) -> BoxFuture<Result<()>> {
    // TODO: Solution here
}
```

#### Expected command and response:
Command:
```
curl -X POST http://localhost:8011 \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "hardhat_setCode",
       "params": ["0x0d2026b3EE6eC71FC6746ADb6311F6d3Ba1C000B", "0xa1a2a3..."]
     }'
```

Response:
```
{"jsonrpc":"2.0", "result":true, "id":1}
```

### **Requirements:**

1. **Implement the Method:**
    - The method should accept `address` of type `Address` and `code` of type `Vec<u8>`.
    - Return an acknowledgment once the bytecode has been set for the given address.

2. **Unit Tests:**
    - Write unit tests ensuring the `hardhat_setCode` method functions correctly.
    - Test with different addresses and bytecode values, including invalid or non-existent ones.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `hardhat_setCode` method.
    - Include details about parameters, return values, and any possible exceptions or errors.
    - Update `SUPPORTED_APIS.md` with updated documentation and examples.
    - (Optional) Add request to `test_endpoints.http` for easier manual verification.

### **Task Checklist:**
- [ ] Implement the `hardhat_setCode` method.
- [ ] Write unit tests for the `hardhat_setCode` method.
- [ ] Add inline documentation for the `hardhat_setCode` method.
- [ ] Update documentation for the `hardhat_dropTransaction` endpoint in `SUPPORTED_APIS.md`.

### **Additional Notes:**
If you're an external contributor wanting to work on this issue, please comment below to notify us. If you have questions about the requirements or need any assistance related to the implementation, don't hesitate to ask!

**Comment by MexicanAce** [comment]
Bumping to `P1` as it's useful for tests in `era-contracts` repo
