### ISSUE TITLE
zks_api: Implement `zks_getBridgeContracts` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#153]
## **Description:**
We need to implement the `zks_getBridgeContracts` method. This function retrieves the L1/L2 addresses of default bridges. Currently we do not support L1 communication but this method is a **requirement for block explorer integration**. We will likely just need to provide an default value for the `l1Erc20DefaultBridge` response.

```rust
/// Returns L1/L2 addresses of default bridges.
fn zks_getBridgeContracts(&self) -> jsonrpc_core::BoxFuture<jsonrpc_core::Result<BridgeAddresses>> {
    not_implemented("zks_getBridgeContracts")
}

// Struct representation for BridgeAddresses 
struct BridgeAddresses {
    l1Erc20DefaultBridge: String,
    l2Erc20DefaultBridge: String,
}
```

#### Expected response
Command:
```
curl -X POST -H "Content-Type: application/json" \
--data '{"jsonrpc": "2.0", "id": 1, "method": "zks_getBridgeContracts", "params": [ ]}' \
"https://mainnet.era.zksync.io"
```

Response:
```
{
    "jsonrpc": "2.0",
    "result": {
        "l1Erc20DefaultBridge": "0x57891966931eb4bb6fb81430e6ce0a03aabde063",
        "l2Erc20DefaultBridge": "0x11f943b2c77b743ab90f4a0ae7d5a4e7fca3e102"
    },
    "id": 1
}
```

### **Requirements:**

1. **Implement the Method:**
    - The method should return a structured response containing the L1 and L2 addresses of the default bridges.

2. **Unit Tests:**
- Write unit tests ensuring the `zks_getBridgeContracts` method functions correctly.
- Test with different transaction hashes, including invalid or non-existent ones.
- Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Append inline Rust documentation (`///` comments) explaining the purpose and usage of the `zks_getBridgeContracts` method.
    - Offer details about return values, and any potential exceptions or errors.

### **Task Checklist:**
- [ ] Implement the `zks_getBridgeContracts` method.
- [ ] Write unit tests for the `zks_getBridgeContracts` method.
- [ ] Add inline documentation for the `zks_getBridgeContracts` method.

### **Additional Notes:**
External contributors interested in taking on this issue should comment below. If there are questions about the requirements or if assistance is needed with any aspect of the implementation, don't hesitate to ask!
