### ISSUE TITLE
hardhat_api: Implement `hardhat_reset` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#275]
## **Description:**
The `hardhat_reset` endpoint is yet to be created. This endpoint should reset the state of the network to a clean state, optionally to a given block number. The reset could be useful in testing environments where a consistent starting point is required across tests. [Hardhat docs for reference](https://hardhat.org/hardhat-network/docs/reference#hardhat_reset), example usage can be found in the [reset feature tests](https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-core/test/internal/hardhat-network/provider/reset.ts).

```rust
// Interface in the `trait`
#[rpc(name = "hardhat_reset")]
fn reset_network(&self, block_number: Option<u64>) -> BoxFuture<Result<bool>>;

// Implementation code in the `impl`
fn reset_network(&self, block_number: Option<u64>) -> BoxFuture<Result<bool>> {
    // TODO: Reset logic here
}
```

**JS implementation:**
```javascript
/**
 * Resets the Hardhat Network to a clean state, optionally to a specific block number.
 *
 * @param blockNumber (Optional) The block number to reset the state to.
 * @returns `true` if the network was successfully reset, otherwise `false`.
 */
export async function resetNetwork(blockNumber?: number): Promise<boolean> {
  const provider = await getHardhatProvider();

  return (await provider.request({
    method: "hardhat_reset",
    params: blockNumber !== undefined ? [{to: blockNumber}] : [],
  })) as boolean;
}
```

#### Expected response
Command for resetting without specifying a block number:
```
curl -X POST http://localhost:8011 \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "hardhat_reset",
       "params": []
     }'
```

Command for resetting to a specific block number:
```
curl -X POST http://localhost:8011 \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "hardhat_reset",
       "params": [{"to": 5}]
     }'
```

Response for both:
```
{"jsonrpc":"2.0", "result":true, "id":1}
```

### **Requirements:**

1. **Implement the API:**
    - The endpoint should effectively reset the network state, and return `true` upon success.
    - Allow resetting to a specific block number if provided.
    - Ensure the method is executed reliably and efficiently, with appropriate error handling.

2. **Unit Tests:**
    - Develop unit tests to confirm the `resetNetwork` method's functionality.
    - Include tests for both resetting to a clean state and to a specified block number, covering various scenarios.

3. **Documentation:**
    - Include inline Rust documentation (`///` comments) to explain the method's purpose, its parameters, return values, and potential edge cases or error situations.
    - Update `SUPPORTED_APIS.md` with the latest documentation, including examples.
    - Include a request in `test_endpoints.http` to simplify manual testing.

### **Task Checklist:**
- [ ] Implement the `resetNetwork` method.
- [ ] Create unit tests for the `resetNetwork` method.
- [ ] Add inline documentation for the `hardhat_reset` endpoint.
- [ ] Update the `hardhat_reset` endpoint documentation in `SUPPORTED_APIS.md`.

### **Additional Notes:**
If you're an external contributor interested in tackling this issue, please leave a comment below to indicate you're on it. Should you need more details on the requirements or assistance with anything related to the implementation, don't hesitate to reach out!

**Comment by MexicanAce** [comment]
Released in `0.1.0-alpha.24`
