### ISSUE TITLE
hardhat_api: Implement `hardhat_setStorageAt` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#276]
## **Description:**
The implementation of the `hardhat_setStorageAt` endpoint is required. This endpoint aims to modify the storage of a contract at a specific slot directly. This feature is particularly useful for testing and debugging purposes, allowing developers to simulate various contract states easily. For further details, refer to the [Hardhat documentation](https://hardhat.org/hardhat-network/docs/reference#hardhat_setstorageat) and examine implementations in similar features through the [Hardhat repository](https://github.com/NomicFoundation/hardhat).

```rust
// Interface in the `trait`
#[rpc(name = "hardhat_setStorageAt")]
fn set_storage_at(&self, contract_address: H160, storage_slot: H256, value: H256) -> BoxFuture<Result<bool>>;

// Implementation code in the `impl`
fn set_storage_at(&self, contract_address: H160, storage_slot: H256, value: H256) -> BoxFuture<Result<bool>> {
    // TODO: Logic to modify storage here
}
```

**JS implementation:**
```javascript
/**
 * Directly modifies the storage of a contract at a specified slot.
 *
 * @param address The contract address whose storage is to be modified.
 * @param slot The storage slot to modify.
 * @param value The value to be set at the specified slot.
 * @returns `true` if the storage was successfully modified, otherwise `false`.
 */
export async function setStorageAt(address: string, slot: string, value: string): Promise<boolean> {
  const provider = await getHardhatProvider();

  return (await provider.request({
    method: "hardhat_setStorageAt",
    params: [address, slot, value],
  })) as boolean;
}
```

#### Expected response
Command to modify a storage slot:
```
curl -X POST http://localhost:8011 \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "hardhat_setStorageAt",
       "params": ["0x1234...", "0x5...", "0xabcd..."]
     }'
```

Response:
```
{"jsonrpc":"2.0", "result":true, "id":1}
```

### **Requirements:**

1. **Implement the API:**
    - The endpoint must be able to modify a contract's storage at a given slot accurately.
    - Ensure the method executes the update reliably and efficiently, with comprehensive error handling.

2. **Unit Tests:**
    - Develop unit tests to validate the functionality of the `setStorageAt` method.
    - Tests should cover various use cases, including setting different values and handling invalid inputs.

3. **Documentation:**
    - Provide inline Rust documentation (`///` comments) explaining the method's functionality, parameters, expected outcomes, and potential error cases.
    - Update the `SUPPORTED_APIS.md` file with the latest documentation, including usage examples.
    - Add a request in `test_endpoints.http` for simpler manual testing.

### **Task Checklist:**
- [ ] Implement the `setStorageAt` method.
- [ ] Create unit tests for the `setStorageAt` method.
- [ ] Add inline documentation for the `hardhat_setStorageAt` endpoint.
- [ ] Update documentation for the `hardhat_setStorageAt` endpoint in `SUPPORTED_APIS.md`.

### **Additional Notes:**
If you're an external contributor interested in working on this issue, please post a comment below to let us know. Should you need clarification on the requirements or assistance with anything related to the implementation, feel free to ask!
