### ISSUE TITLE
eth_api: Implement `new_filter` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#36]
### **Description:**
We currently have a stub for the [`new_filter`](https://github.com/matter-labs/era-test-node/blob/3539ad0a87f5cc5350b346bace874f4d966714b3/src/node.rs#L989) method, which is expected to handle creating a new filter based on a given criteria. We need to fully implement this method, ensure it's tested properly, and documented.

```rust
/// Creates a filter object, based on filter options, to notify when the state changes (logs).
fn new_filter(&self, _filter: Filter) -> jsonrpc_core::BoxFuture<jsonrpc_core::Result<U256>> {
    not_implemented("new_filter")
}
```

#### Expected response
Command:
```
# Note: Using mainnet URL for demonstration purposes
curl -X POST https://mainnet.era.zksync.io \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "eth_newFilter",
       "params": [{
          "fromBlock": "0x1",
          "toBlock": "latest",
          "address": "0x11f943b2c77b743AB90f4A0Ae7d5A4e7FCA3E102",
          "topics": ["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"]
       }]
     }'
```
Response:
```
{"jsonrpc":"2.0","result":"0x247bc98d33cd6cfd9b2311cc5e129569a5bd4399d34fd1d456a78eeedebb4cfa","id":1}
```

### **Requirements:**

1. **Implement the Method:**
    - The method should take a `Filter` as an argument.
    - The method should create a new filter based on the given criteria and return a `U256` id for the created filter.

2. **Unit Tests:**
    - Write unit tests ensuring the `new_filter` method is working correctly.
    - Ensure edge cases are tested.
    - Ensure failures and errors are handled appropriately.

3. **Inline Documentation:**
    - Add inline Rust documentation (`///` comments) to describe the purpose and usage of the `new_filter` method.
    - Include any relevant information about parameters, return values, and potential errors/exceptions.

### **Task Checklist:**
- [ ] Implement the `new_filter` method.
- [ ] Write unit tests for the `new_filter` method.
- [ ] Add inline documentation for the `new_filter` method.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!
