### ISSUE TITLE
eth_api: Implement `new_block_filter` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#37]
### **Description:**
We currently have a stub for the [`new_block_filter`](https://github.com/matter-labs/era-test-node/blob/3539ad0a87f5cc5350b346bace874f4d966714b3/src/node.rs#L993) method, which is expected to handle the creation of a new filter for receiving notifications when a new block is mined. We need to fully implement this method, ensure it's tested properly, and documented.

```rust
/// Creates a filter that notifies when a new block is mined.
fn new_block_filter(&self) -> jsonrpc_core::BoxFuture<jsonrpc_core::Result<U256>> {
    not_implemented("new_block_filter")
}
```

#### Expected response
Command:
```curl
# Note: Using mainnet URL for demonstration purposes
curl -X POST https://mainnet.era.zksync.io \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "eth_newBlockFilter",
       "params": []
     }'
```
Response:
```
{"jsonrpc":"2.0","result":"0x72df37711637fcd85355867f08abc64c17dc04719d84da846a3a9f9ca22c4265","id":1}
```

### **Requirements:**

1. **Implement the Method:**
    - The method should not take any arguments.
    - It should create a new filter that notifies the caller when a new block is mined.
    - Return a `U256` id for the created filter.

2. **Unit Tests:**
    - Write unit tests ensuring the `new_block_filter` method is working correctly.
    - Ensure edge cases are tested.
    - Ensure failures and errors are handled appropriately.

3. **Inline Documentation:**
    - Add inline Rust documentation (`///` comments) to describe the purpose and usage of the `new_block_filter` method.
    - Include any relevant information about the return values and potential errors/exceptions.

### **Task Checklist:**
- [ ] Implement the `new_block_filter` method.
- [ ] Write unit tests for the `new_block_filter` method.
- [ ] Add inline documentation for the `new_block_filter` method.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!
