### ISSUE TITLE
eth_api: Implement `uninstall_filter` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#38]
### **Description:**
We currently have a placeholder for the [`uninstall_filter`](https://github.com/matter-labs/era-test-node/blob/3539ad0a87f5cc5350b346bace874f4d966714b3/src/node.rs#L997C8-L997C24) method, which is anticipated to handle the removal of an existing filter based on a provided filter ID. 

```rust
/// Uninstalls a previously created filter by its ID.
fn uninstall_filter(&self, filter_id: U256) -> jsonrpc_core::BoxFuture<jsonrpc_core::Result<bool>> {
    not_implemented("uninstall_filter")
}
```

#### Expected response

Command:
```
# Note: Using mainnet URL for demonstration purposes
curl -X POST https://mainnet.era.zksync.io \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "eth_uninstallFilter",
       "params": ["0x72df37711637fcd85355867f08abc64c17dc04719d84da846a3a9f9ca22c4265"]
     }'
```
Response:
```
{"jsonrpc":"2.0","result":false,"id":1}
```

### **Requirements:**

1. **Implement the Method:**
    - The method should take a `U256` filter ID as its argument.
    - Remove the filter associated with the provided ID.
    - Return a boolean indicating the success or failure of the uninstallation.

2. **Unit Tests:**
    - Write unit tests ensuring the `uninstall_filter` method operates correctly.
    - Address potential edge cases in your testing.
    - Implement error-handling measures for potential failures.

3. **Inline Documentation:**
    - Include inline Rust documentation (`///` comments) to outline the purpose and application of the `uninstall_filter` method.
    - Provide details regarding parameters, return values, and any potential errors or exceptions.

### **Task Checklist:**
- [ ] Implement the `uninstall_filter` method.
- [ ] Write unit tests for the `uninstall_filter` method.
- [ ] Include inline documentation for the `uninstall_filter` method.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!
