### ISSUE TITLE
eth_api: Implement `new_pending_transaction_filter` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#39]
### **Description:**
We currently have a placeholder for the [`new_pending_transaction_filter`](https://github.com/matter-labs/era-test-node/blob/3539ad0a87f5cc5350b346bace874f4d966714b3/src/node.rs#L1001C8-L1001C38) method, which is designed to establish a filter that notifies when new pending transactions enter the transaction pool. 

```rust
/// Creates a filter to notify when new pending transactions arise.
fn new_pending_transaction_filter(&self) -> jsonrpc_core::BoxFuture<jsonrpc_core::Result<U256>> {
    not_implemented("new_pending_transaction_filter")
}
```

#### Expected response

Command:
```
# Note: Using mainnet URL for demonstration purposes
curl -X POST https://mainnet.era.zksync.io \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "eth_newPendingTransactionFilter",
       "params": []
     }'
```
Response:
```
{"jsonrpc":"2.0","result":"0xf86f90e83fd8a20ed75b6f7ed364c301a551abc98d5318d8d12e5ea4de7aa15a","id":1}
```

### **Requirements:**

1. **Implement the Method:**
    - The method doesn't require any arguments.
    - It should establish a new filter and return a `U256` id for the created filter that's oriented towards pending transactions.

2. **Unit Tests:**
    - Write unit tests to confirm the `new_pending_transaction_filter` method's functionality.
    - Consider and test for potential edge cases.
    - Ensure that potential errors and exceptions are managed appropriately.

3. **Inline Documentation:**
    - Add inline Rust documentation (`///` comments) to define the purpose and implementation of the `new_pending_transaction_filter` method.
    - Include any relevant information about the return values and potential errors/exceptions.

### **Task Checklist:**
- [ ] Implement the `new_pending_transaction_filter` method.
- [ ] Write unit tests for the `new_pending_transaction_filter` method.
- [ ] Include inline documentation for the `new_pending_transaction_filter` method.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!
