### ISSUE TITLE
eth_api: Implement `get_logs` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#40]
### **Description:**
We currently have a placeholder for the [`get_logs`](https://github.com/matter-labs/era-test-node/blob/3539ad0a87f5cc5350b346bace874f4d966714b3/src/node.rs#L1007) method, which is expected to retrieve the logs based on a filter object.

```rust
/// Retrieves logs based on a filter object.
fn get_logs(&self, filter: Filter) -> jsonrpc_core::BoxFuture<jsonrpc_core::Result<Vec<Log>>> {
    not_implemented("get_logs")
}
```

#### Expected response

Command:
```
# Note: Using mainnet URL for demonstration purposes
curl -X POST https://mainnet.era.zksync.io \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "eth_getLogs",
       "params": [{
          "fromBlock": "0x1",
          "toBlock": "latest",
          "address": "0x11f943b2c77b743AB90f4A0Ae7d5A4e7FCA3E102",
          "topics": ["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"]
       }]
     }'
```
Response:
```
{"jsonrpc":"2.0","result":[],"id":1}
```

### **Requirements:**

1. **Implement the Method:**
    - The method should take a `Filter` as its argument.
    - Based on the provided filter, it should fetch and return the relevant logs as a `Vec<Log>`.

2. **Unit Tests:**
    - Write unit tests to ensure the `get_logs` method functions correctly.
    - Account for potential edge cases in the tests.
    - Ensure that errors and exceptions are handled appropriately.

3. **Inline Documentation:**
    - Add inline Rust documentation (`///` comments) explaining the purpose and function of the `get_logs` method.
    - Include any relevant information about the return values and potential errors/exceptions.

### **Task Checklist:**
- [ ] Implement the `get_logs` method.
- [ ] Write unit tests for the `get_logs` method.
- [ ] Add inline documentation for the `get_logs` method.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!
