### ISSUE TITLE
eth_api: Implement `get_filter_logs` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#41]
### **Description:**
We have identified the need to implement the [`get_filter_logs`](https://github.com/matter-labs/era-test-node/blob/3539ad0a87f5cc5350b346bace874f4d966714b3/src/node.rs#L1014C8-L1014C23) method. This method should fetch logs pertaining to a specific filter identifier.

```rust
/// Fetches logs for a specific filter identifier.
fn get_filter_logs(&self, filter_id: U256) -> jsonrpc_core::BoxFuture<jsonrpc_core::Result<Vec<Log>>> {
    not_implemented("get_filter_logs")
}
```

#### Expected response
Command:
```
# Note: Using mainnet URL for demonstration purposes
curl -X POST https://mainnet.era.zksync.io \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "eth_getFilterLogs",
       "params": ["0xfd31da6b480fde036546fbced636b8aa6b0e03ec32fe5a0ff4d2901fdf3480d9"]
     }'
```
Response:
```
{"jsonrpc":"2.0","result":[],"id":1}
```

### **Requirements:**

1. **Implement the Method:**
    - The method should accept a `U256` filter ID as its argument.
    - Based on the provided filter ID, it should retrieve and return the associated logs as a `Vec<Log>`.

2. **Unit Tests:**
    - Write unit tests to ensure the `get_filter_logs` method operates as expected.
    - Include potential edge cases in your tests.
    - Ensure that failures, errors, and exceptions are managed properly.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) to convey the purpose and utility of the `get_filter_logs` method.
    - Include any relevant information about the return values and potential errors/exceptions.

### **Task Checklist:**
- [ ] Implement the `get_filter_logs` method.
- [ ] Write unit tests for the `get_filter_logs` method.
- [ ] Include inline documentation for the `get_filter_logs` method.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!

**Comment by MexicanAce** [comment]
Resolved in #130
