### ISSUE TITLE
eth_api: Implement `get_filter_changes` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#42]
### **Description:**
We need to implement the [`get_filter_changes`](https://github.com/matter-labs/era-test-node/blob/3539ad0a87f5cc5350b346bace874f4d966714b3/src/node.rs#L1021C8-L1021C26) method. This method aims to retrieve the changes associated with a specific filter ID, ensuring a more dynamic interaction. Polling method for a filter, which returns an array of logs which occurred since last poll. Filter must be created by calling either [eth_newFilter](https://docs.infura.io/networks/ethereum/json-rpc-methods/filter-methods/eth_newfilter) or [eth_newBlockFilter](https://docs.infura.io/networks/ethereum/json-rpc-methods/filter-methods/eth_newblockfilter).

```rust
/// Retrieves the changes associated with a specific filter ID.
fn get_filter_changes(&self, filter_id: U256) -> jsonrpc_core::BoxFuture<jsonrpc_core::Result<Vec<Change>>> {
    not_implemented("get_filter_changes")
}
```

### **Requirements:**

1. **Implement the Method:**
    - This method should take in a `U256` filter ID.
    - Based on this ID, it should return the changes in a `Vec<Change>` format associated with the filter.

2. **Unit Tests:**
    - Write unit tests to ensure the correct operation of the `get_filter_changes` method.
    - Ensure that you cover various edge cases.
    - Ensure failures and exceptions are handled aptly.

3. **Inline Documentation:**
    - Include inline Rust documentation (`///` comments) detailing the function and utility of the `get_filter_changes` method.
    - Include any relevant information about the return values and potential errors/exceptions.

### **Task Checklist:**
- [ ] Implement the `get_filter_changes` method.
- [ ] Write unit tests for the `get_filter_changes` method.
- [ ] Include inline documentation for the `get_filter_changes` method.

### **Additional Notes:**
If you are an external contributor and are considering working on this issue, please comment below so we are aware. Should you need clarification on any aspect of the requirements or seek assistance regarding the implementation, do not hesitate to ask.
