### ISSUE TITLE
eth_api: Implement `get_block_transaction_count_by_number` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#43]
### **Description:**
We need to implement the [`get_block_transaction_count_by_number`](https://github.com/matter-labs/era-test-node/blob/3539ad0a87f5cc5350b346bace874f4d966714b3/src/node.rs#L1028C8-L1028C45) method. This function returns the number of transactions in the block with the given block number.

```rust
/// Retrieves the number of transactions in a block by block number.
fn get_block_transaction_count_by_number(&self, block_number: BlockNumber) -> jsonrpc_core::BoxFuture<jsonrpc_core::Result<U256>> {
    not_implemented("get_block_transaction_count_by_number")
}
```

#### Expected response
Command:
```
# Note: Using mainnet URL for demonstration purposes
curl -X POST https://mainnet.era.zksync.io \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "eth_getBlockTransactionCountByNumber",
       "params": ["0xA4CDA7"]
     }'
```
Response:
```
{"jsonrpc":"2.0","result":"0x2","id":1}
```

### **Requirements:**

1. **Implement the Method:**
    - The method should take in a `BlockNumber`.
    - It should return the count of transactions in the specified block as a `U256`.

2. **Unit Tests:**
    - Write unit tests ensuring the `get_block_transaction_count_by_number` method functions correctly.
    - Test various edge cases, including blocks with no transactions.
    - Properly handle potential exceptions and errors.

3. **Inline Documentation:**
    - Write inline Rust documentation (`///` comments) explaining the purpose and usage of the `get_block_transaction_count_by_number` method.
    - Include details on parameters, return values, and any possible exceptions or errors.

### **Task Checklist:**
- [ ] Implement the `get_block_transaction_count_by_number` method.
- [ ] Write unit tests for the `get_block_transaction_count_by_number` method.
- [ ] Add inline documentation for the `get_block_transaction_count_by_number` method.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!
