### ISSUE TITLE
eth_api: Implement `get_block_transaction_count_by_hash` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#44]
### **Description:**
We are tasked with implementing the [`get_block_transaction_count_by_hash`](https://github.com/matter-labs/era-test-node/blob/3539ad0a87f5cc5350b346bace874f4d966714b3/src/node.rs#L1035C8-L1035C43) method. This function returns the number of transactions in the block with the given block hash.

```rust
/// Retrieves the number of transactions in a block by block hash.
fn get_block_transaction_count_by_hash(&self, block_hash: H256) -> jsonrpc_core::BoxFuture<jsonrpc_core::Result<U256>> {
    not_implemented("get_block_transaction_count_by_hash")
}
```

#### Expected response

Command:
```
# Note: Using mainnet URL for demonstration purposes
curl -X POST https://mainnet.era.zksync.io \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "eth_getBlockTransactionCountByHash",
       "params": ["0x3e72b04fda2b20d09bc97380dfdbd8b9e78272829cd9b337a064ab533bc6502d"]
     }'
```
Response:
```
{"jsonrpc":"2.0","result":,"id":1}
```

### **Requirements:**

1. **Implement the Method:**
    - The method should accept a `H256` block hash as its parameter.
    - It should then return the count of transactions present in the block corresponding to the given hash, formatted as a `U256`.

2. **Unit Tests:**
    - Write unit tests ensuring the `get_block_transaction_count_by_hash` method behaves as expected.
    - Test a variety of edge cases, including blocks without transactions.
    - Include any relevant information about the return values and potential errors/exceptions.

3. **Inline Documentation:**
    - Add inline Rust documentation (`///` comments) to describe the functionality and usage of the `get_block_transaction_count_by_hash` method.
    - Include any relevant information about the return values and potential errors/exceptions.

### **Task Checklist:**
- [ ] Implement the `get_block_transaction_count_by_hash` method.
- [ ] Write unit tests for the `get_block_transaction_count_by_hash` method.
- [ ] Add inline documentation for the `get_block_transaction_count_by_hash` method.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!
