### ISSUE TITLE
eth_api: Implement `get_storage` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#45]
### **Description:**
We need to implement the [`get_storage`](https://github.com/matter-labs/era-test-node/blob/3539ad0a87f5cc5350b346bace874f4d966714b3/src/node.rs#L1042C8-L1042C19) method, which will be responsible for fetching the storage value from a position in a contract.

```rust
/// Retrieves the storage value from a position in a contract.
fn get_storage(&self, address: H160, position: U256, block: Option<BlockIdentifier>) -> jsonrpc_core::BoxFuture<jsonrpc_core::Result<Option<H256>>> {
    not_implemented("get_storage")
}
```

#### Expected response
Command:
```
# Note: Using mainnet URL for demonstration purposes
curl -X POST https://mainnet.era.zksync.io \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "eth_getStorageAt",
       "params": ["0x123456789abcdef123456789abcdef1234567890", "0x0", "latest"]
     }'
```
Response:
```
{"jsonrpc":"2.0","result":"0x0000000000000000000000000000000000000000000000000000000000000000","id":1}
```

### **Requirements:**

1. **Implement the Method:**
    - This method should take in three parameters: an `H160` address, a `U256` position, and an optional `BlockIdentifier` to specify the block from which the storage should be retrieved.
    - It should return an `Option<H256>` value representing the storage at the specified position.

2. **Unit Tests:**
    - Write unit tests to ensure that the `get_storage` method is functioning correctly.
    - Ensure that any potential exceptions and errors, like an invalid address or position, are correctly handled.

3. **Inline Documentation:**
    - Add inline Rust documentation (`///` comments) detailing the purpose and usage of the `get_storage` method.
    - Include any relevant information about the return values and potential errors/exceptions.

### **Task Checklist:**
- [ ] Implement the `get_storage` method.
- [ ] Write unit tests for the `get_storage` method.
- [ ] Add inline documentation for the `get_storage` method.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!

**Comment by nbaztec** [comment]
@MexicanAce  I see that currently we do not have a storage (root) per block and only a 1-tier storage. For implementing `eth_getStorageAt` we also have the additional `block` parameter to get storage at a height. Do we have an intention of supporting a per height storage?

**Comment by georgewhewell** [comment]
> @MexicanAce I see that currently we do not have a storage (root) per block and only a 1-tier storage. For implementing `eth_getStorageAt` we also have the additional `block` parameter to get storage at a height. Do we have an intention of supporting a per height storage?

imo yes, it's quite important- it would be very confusing for people debug issues that arise when using tooling which expects this parameter to be respected and it is not. other dev nodes (e.g anvil) do implement this
