### ISSUE TITLE
eth_api: Implement `get_transaction_by_block_hash_and_index` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#46]
### **Description:**
We need to implement the [`get_transaction_by_block_hash_and_index`](https://github.com/matter-labs/era-test-node/blob/3539ad0a87f5cc5350b346bace874f4d966714b3/src/node.rs#L1051C8-L1051C47) method. This function is designed to retrieve a specific transaction from a block, given the block's hash and the transaction's index within that block.

```rust
/// Fetches a transaction from a block based on its hash and its position index.
fn get_transaction_by_block_hash_and_index(&self, block_hash: H256, index: U256) -> jsonrpc_core::BoxFuture<jsonrpc_core::Result<Option<Transaction>>> {
    not_implemented("get_transaction_by_block_hash_and_index")
}
```

#### Expected response
Command:
```
# Note: Using mainnet URL for demonstration purposes
curl -X POST https://mainnet.era.zksync.io \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "eth_getTransactionByBlockHashAndIndex",
       "params": ["0xfb8718465e855a68e2603b0e21c1b974288d4628419792aa89b68e461666934b", "0x0"]
     }'
```
Response:
```
{"jsonrpc":"2.0","result":,"id":1}
```

### **Requirements:**

1. **Implement the Method:**
    - This function will accept a `H256` block hash and a `U256` index representing the transaction's position within the block.
    - It should return an `Option<Transaction>` which represents the specific transaction, or `None` if it doesn't exist.

2. **Unit Tests:**
    - Write unit tests to ensure the `get_transaction_by_block_hash_and_index` method is working accurately.
    - Take into account various scenarios and edge cases, including non-existent transaction indices.
    - Ensure that all possible errors, such as an invalid block hash or index, are properly addressed.

3. **Inline Documentation:**
    - Add inline Rust documentation (`///` comments) explaining the function and its usage.
    - Include any relevant information about the return values and potential errors/exceptions.

### **Task Checklist:**
- [ ] Implement the `get_transaction_by_block_hash_and_index` method.
- [ ] Write unit tests for the `get_transaction_by_block_hash_and_index` method.
- [ ] Add inline documentation for the `get_transaction_by_block_hash_and_index` method.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!
