### ISSUE TITLE
eth_api: Implement `get_transaction_by_block_number_and_index` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#47]
### **Description:**
We need to implement the [`get_transaction_by_block_number_and_index`](https://github.com/matter-labs/era-test-node/blob/3539ad0a87f5cc5350b346bace874f4d966714b3/src/node.rs#L1059C8-L1059C49) method. This function aims to retrieve a specific transaction from a block, using the block's number and the transaction's index within that block.

```rust
/// Fetches a transaction from a block based on its number and its position index.
fn get_transaction_by_block_number_and_index(&self, block_number: U256, index: U256) -> jsonrpc_core::BoxFuture<jsonrpc_core::Result<Option<Transaction>>> {
    not_implemented("get_transaction_by_block_number_and_index")
}
```

#### Expected response
Command:
```
# Note: Using mainnet URL for demonstration purposes
curl -X POST https://mainnet.era.zksync.io \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "eth_getTransactionByBlockNumberAndIndex",
       "params": ["0x123456", "0x0"]
     }'
```
Response:
```
{"jsonrpc":"2.0","result":{"hash":"0x3508f99da6743a97d335138d2a5641b460a270c374b468abf6375499a58466c2","nonce":"0x35","blockHash":"0xeb118419f46a84d5cc96cc9d7d048c7f3f2f9b521789226dbde7bc9f8355894e","blockNumber":"0x123456","transactionIndex":"0x0","from":"0xe8a040af47550deae8655d96e4aa9b0b6afe6247","to":"0x5aea5775959fbc2557cc8789bc1bf90a239d9a91","value":"0x0","gasPrice":"0xee6b280","gas":"0x6ddd0","input":"0x2e1a7d4d00000000000000000000000000000000000000000000000014d1120d7b160000","v":"0x0","r":"0xdccb7fd941ecfc77f1daf3599f3584be694d0ab291f348c8d97be694edac6337","s":"0x4fe2e5df3fe11edf7681c60ccbc4eb29dbad029ec185147d4f1d6e9fc54b38f3","type":"0x2","maxFeePerGas":"0xee6b280","maxPriorityFeePerGas":"0xee6b280","chainId":"0x144","l1BatchNumber":"0x325b","l1BatchTxIndex":"0xcc"},"id":1}
```

### **Requirements:**

1. **Implement the Method:**
    - The method should take a `U256` block number and a `U256` index which indicates the transaction's position within the block.
    - It should then return an `Option<Transaction>` representing the desired transaction, or `None` if it's not found.

2. **Unit Tests:**
    - Write unit tests to validate the functionality of the `get_transaction_by_block_number_and_index` method.
    - Ensure to cover various scenarios, including non-existent transaction indices and invalid block numbers.
    - Proper error handling for scenarios like invalid block numbers or indices should also be tested.

3. **Inline Documentation:**
    - Add inline Rust documentation (`///` comments) detailing the method's purpose and functionality.
    - Include any relevant information about the return values and potential errors/exceptions.

### **Task Checklist:**
- [ ] Implement the `get_transaction_by_block_number_and_index` method.
- [ ] Write unit tests for the `get_transaction_by_block_number_and_index` method.
- [ ] Include inline documentation for the `get_transaction_by_block_number_and_index` method.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!

**Comment by MexicanAce** [comment]
Resolved in #159
