### ISSUE TITLE
eth_api: Implement `protocol_version` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#48]
### **Description:**
The [`protocol_version`](https://github.com/matter-labs/era-test-node/blob/3539ad0a87f5cc5350b346bace874f4d966714b3/src/node.rs#L1067C8-L1067C24) method requires implementation. This function is meant to retrieve the current protocol version used by the node.

```rust
/// Gets the current protocol version of the node.
fn protocol_version(&self) -> jsonrpc_core::BoxFuture<jsonrpc_core::Result<U256>> {
    not_implemented("protocol_version")
}
```

#### Expected response
Command:
```
# Note: Using mainnet URL for demonstration purposes
curl -X POST https://mainnet.era.zksync.io \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "eth_protocolVersion",
       "params": []
     }'

```
Response:
```
{"jsonrpc":"2.0","result":"zks/1","id":1}
```

### **Requirements:**

1. **Implement the Method:**
    - The method should promptly return a `U256` value representing the protocol version of the node.
    - Ensure the returned protocol version is accurate and consistent with the node's operation.

2. **Unit Tests:**
    - Write unit tests to validate the functionality of the `protocol_version` method.
    - Make sure that the returned version matches expected values, especially after any potential upgrades or changes to the node.

3. **Inline Documentation:**
    - Add inline Rust documentation (`///` comments) explaining the method's purpose and behavior.
    - Include any relevant information about the return values and potential errors/exceptions.

### **Task Checklist:**
- [ ] Implement the `protocol_version` method.
- [ ] Write unit tests for the `protocol_version` method.
- [ ] Include inline documentation for the `protocol_version` method.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!
