### ISSUE TITLE
eth_api: Implement `syncing` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#49]
### **Description:**
The [`syncing`](https://github.com/matter-labs/era-test-node/blob/3539ad0a87f5cc5350b346bace874f4d966714b3/src/node.rs#L1071C8-L1071C15) method requires implementation. This function is designed to determine if the node is currently syncing or is fully synced with the network.

```rust
/// Retrieves the syncing status of the node.
fn syncing(&self) -> jsonrpc_core::BoxFuture<jsonrpc_core::Result<SyncStatus>> {
    not_implemented("syncing")
}
```

#### Expected response
Command:
```
# Note: Using mainnet URL for demonstration purposes
curl -X POST https://mainnet.era.zksync.io -H "Content-Type: application/json" --data '{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "eth_syncing",
  "params": []
}'
```
Response:
```
{"jsonrpc":"2.0","result":false,"id":1}
```

### **Requirements:**

1. **Implement the Method:**
    - The method should return a `SyncStatus` object, which could be either:
        - `false` if the node is not syncing.
        - An object detailing the sync status, including fields such as `startingBlock`, `currentBlock`, and `highestBlock`.
    - Ensure the method accurately determines and reports the node's sync status.

2. **Unit Tests:**
    - Write unit tests to confirm the correctness of the `syncing` method.
    - Ensure tests cover scenarios where the node is syncing, is fully synced, or encounters issues during the syncing process.

3. **Inline Documentation:**
    - Add inline Rust documentation (`///` comments) explaining the function's purpose, output, and behavior.
    - Include any relevant information about the return values and potential errors/exceptions.

### **Task Checklist:**
- [ ] Implement the `syncing` method.
- [ ] Write unit tests for the `syncing` method.
- [ ] Include inline documentation for the `syncing` method.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!
