### ISSUE TITLE
eth_api: Implement `accounts` method

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#50]
### **Description:**
The [`accounts`](https://github.com/matter-labs/era-test-node/blob/3539ad0a87f5cc5350b346bace874f4d966714b3/src/node.rs#L1078C8-L1078C16) method needs to be implemented. The purpose of this method is to retrieve a list of accounts owned by the client.

```rust
/// Retrieves the list of accounts owned by the client.
fn accounts(&self) -> jsonrpc_core::BoxFuture<jsonrpc_core::Result<Vec<Address>>> {
    not_implemented("accounts")
}
```

#### Expected response
Command:
```
# Note: Using mainnet URL for demonstration purposes
curl -X POST https://mainnet.era.zksync.io \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "eth_accounts",
       "params": []
     }'
```
Response:
```
{"jsonrpc":"2.0","result":[],"id":1}
```

### **Requirements:**

1. **Implement the Method:**
    - The method should return a list (`Vec`) of `Address` types, representing the accounts owned by the client.
    - Ensure the method fetches the accounts reliably and efficiently.

2. **Unit Tests:**
    - Write unit tests to verify the functionality of the `accounts` method.
    - Ensure coverage for scenarios where the client has multiple accounts, no accounts, or encounters issues retrieving the accounts.

3. **Inline Documentation:**
    - Add inline Rust documentation (`///` comments) detailing the method's purpose, return values, and any potential edge cases or error scenarios.
    - Include any relevant information about the return values and potential errors/exceptions.

### **Task Checklist:**
- [ ] Implement the `accounts` method.
- [ ] Write unit tests for the `accounts` method.
- [ ] Add inline documentation for the `accounts` method.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!

**Comment by dutterbutter** [comment]
Closed in #139
