### ISSUE TITLE
checklist:  Implement `eth_` namespace API 

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#51]
## Description 

To ensure compatibility with Ethereum tooling and integrations, we need to implement the eth_ namespace API endpoints as part of our JSON-RPC interface. This will allow clients to interact with our node using the same methods they would with a standard Ethereum client. The below tasks are to be implemented to successfully close this checklist. 

### Task Checklist 

- [ ] https://github.com/matter-labs/era-test-node/issues/36
- [ ] https://github.com/matter-labs/era-test-node/issues/37
- [ ] https://github.com/matter-labs/era-test-node/issues/38
- [ ] https://github.com/matter-labs/era-test-node/issues/39
- [ ] https://github.com/matter-labs/era-test-node/issues/40
- [ ] https://github.com/matter-labs/era-test-node/issues/41
- [ ] https://github.com/matter-labs/era-test-node/issues/42
- [ ] https://github.com/matter-labs/era-test-node/issues/43
- [ ] https://github.com/matter-labs/era-test-node/issues/44
- [ ] https://github.com/matter-labs/era-test-node/issues/45
- [ ] https://github.com/matter-labs/era-test-node/issues/46
- [ ] https://github.com/matter-labs/era-test-node/issues/47
- [ ] https://github.com/matter-labs/era-test-node/issues/48
- [ ] https://github.com/matter-labs/era-test-node/issues/49
- [ ] https://github.com/matter-labs/era-test-node/issues/50

**Comment by nbaztec** [comment]
Think this can be closed.
