### ISSUE TITLE
debug_api: Implement `debug_traceBlockByNumber` API endpoint

### ISSUE THREAD

**Issue by MexicanAce** [matter-labs/era-test-node#64]
### **Description:**
The `debug_traceBlockByNumber` endpoint needs to be implemented. The purpose of this endpoint is to return structured traces for operations within the block of the specified block number.

```rust
// Interface in the `trait`
#[rpc(name = "debug_traceBlockByNumber")]
fn trace_block_by_number(
    &self,
    block: BlockNumber,
    options: Option<TracerConfig>,
) -> BoxFuture<Result<Vec<ResultDebugCall>>>;

// Actual code in the `impl`
fn trace_block_by_number(
    &self,
    block: BlockNumber,
    options: Option<TracerConfig>,
) -> BoxFuture<Result<Vec<ResultDebugCall>>> {
    // TODO: Solution here
}
```

#### Expected response
Command returns proper response:
```
curl -X POST http://localhost:8011 \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "debug_traceBlockByNumber",
       "params": ["latest"]
     }'
```

### **Requirements:**

1. **Implement the API:**
    - The endpoint should return a populated `Vec<ResultDebugCall>`.
    - Ensure the method executes the call reliably and efficiently.
    - Ensure errors are properly returned (with revert reasons and data).

2. **Unit Tests:**
    - Write unit tests to verify the functionality of the `trace_block_by_number` method.
    - Ensure coverage for multiple edge-case scenarios.

3. **Documentation:**
    - Add inline Rust documentation (`///` comments) detailing the method's purpose, return values, and any potential edge cases or error scenarios.
    - Update `SUPPORTED_APIS.md` with updated documentation and examples.
    - (Optional) Add request to `test_endpoints.http` for easier manual verification.

### **Task Checklist:**
- [ ] Implement the `trace_block_by_number` method.
- [ ] Write unit tests for the `trace_block_by_number` method.
- [ ] Add inline documentation for the `debug_traceBlockByNumber` endpoint.
- [ ] Update documentation for the `debug_traceBlockByNumber` endpoint in `SUPPORTED_APIS.md`.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!
