### ISSUE TITLE
debug_api: Implement `debug_traceTransaction` API endpoint

### ISSUE THREAD

**Issue by MexicanAce** [matter-labs/era-test-node#65]
### **Description:**
The `debug_traceTransaction` endpoint needs to be implemented. The purpose of this endpoint is to return a structured trace of the execution of the specified transaction.

```rust
// Interface in the `trait`
#[rpc(name = "debug_traceTransaction")]
fn trace_transaction(
    &self,
    tx_hash: H256,
    options: Option<TracerConfig>,
) -> BoxFuture<Result<Option<DebugCall>>>;

// Actual code in the `impl`
fn trace_transaction(
    &self,
    tx_hash: H256,
    options: Option<TracerConfig>,
) -> BoxFuture<Result<Option<DebugCall>>> {
    // TODO: Solution here
}
```

#### Expected response
Command returns proper response:
```
curl -X POST http://localhost:8011 \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "debug_traceTransaction",
       "params": ["0x0000000000000000000000000000000000000000000000000000000000000000"]
     }'
```

### **Requirements:**

1. **Implement the API:**
    - The endpoint should return a populated `Option<DebugCall>`.
    - Ensure the method executes the call reliably and efficiently.
    - Ensure errors are properly returned (with revert reasons and data).

2. **Unit Tests:**
    - Write unit tests to verify the functionality of the `trace_transaction` method.
    - Ensure coverage for multiple edge-case scenarios.

3. **Documentation:**
    - Add inline Rust documentation (`///` comments) detailing the method's purpose, return values, and any potential edge cases or error scenarios.
    - Update `SUPPORTED_APIS.md` with updated documentation and examples.
    - (Optional) Add request to `test_endpoints.http` for easier manual verification.

### **Task Checklist:**
- [ ] Implement the `trace_transaction` method.
- [ ] Write unit tests for the `trace_transaction` method.
- [ ] Add inline documentation for the `debug_traceTransaction` endpoint.
- [ ] Update documentation for the `debug_traceTransaction` endpoint in `SUPPORTED_APIS.md`.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!

**Comment by crystalin** [comment]
@MexicanAce do this include supporting custom javascript tracer ? I believe this would significantly increase the scope.
Otherwise which tracer should be supported ?

**Comment by MexicanAce** [comment]
I don't _think_ we need to support custom JavaScript tracer, but could you point me to an example of what you mean by this?

The intent was to design the endpoint as similar to [the zkSync `api_server` implementation](https://era.zksync.io/docs/api/api.html#debug-tracetransaction) which pulls it from a database table:
* https://github.com/matter-labs/zksync-era/blob/main/core/bin/zksync_core/src/api_server/web3/namespaces/debug.rs#L99
* https://github.com/matter-labs/zksync-era/blob/main/core/lib/dal/src/transactions_dal.rs#L1049

This structure of the trace comes from the transaction results:
* https://github.com/matter-labs/zksync-era/blob/main/core/lib/dal/src/transactions_dal.rs#L474C2-L474C2
* https://github.com/matter-labs/zksync-era/blob/main/core/lib/types/src/tx/mod.rs#L39

We do something very similar already with the `ShowCalls` flag for the binary: https://github.com/matter-labs/era-test-node/blob/main/src/node.rs#L1011

**Comment by crystalin** [comment]
Yes sure,

If you look at the api_server implementation you link, they provide a link to the [TraceConfig documentation](https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#traceconfig) which contains:

```
tracer: STRING. Name for built-in tracer or Javascript expression. See below for more details.
```

The javascript expression is real javascript used to interpret (server-side) the transaction debug data (This allows custom traces used some Eth debug service (like blockscout IIRC), without having to generate/transfer a huge amount of data).

Here is one of the tracer we support in Moonbeam API for ex:
https://raw.githubusercontent.com/moonbeam-foundation/moonbeam/master/archived_tests/util/tracer/blockscout_tracer.min.json

**Comment by MexicanAce** [comment]
TIL about the `Javascript expression`... that sounds... dangerous (from a security perspective) 🤔 

Either way, for this ticket let's not include support for a custom javascript tracer.

As for the tracer that should be reported, let me get back to you after some investigation. For now, here's the best definition I can get you: https://github.com/matter-labs/zksync-era/blob/main/core/lib/types/src/vm_trace.rs
