### ISSUE TITLE
evm_api: Implement `evm_increaseTime` API endpoint

### ISSUE THREAD

**Issue by MexicanAce** [matter-labs/era-test-node#66]
### **Description:**
The `evm_increaseTime` endpoint needs to be implemented. The purpose of this endpoint is to jump forward in time by the given amount of time, in seconds. [Ganache docs for reference](https://ganache.dev/#evm_increaseTime).

```rust
// Interface in the `trait`
#[rpc(name = "evm_increaseTime")]
fn increase_time(
    &self,
    time_delta: U64,
) -> BoxFuture<Result<U64>>;

// Actual code in the `impl`
fn increase_time(
    &self,
    time_delta: U64,
) -> BoxFuture<Result<U64>> {
    // TODO: Solution here
}
```

#### Expected response
Command returns proper response:
```
curl -X POST http://localhost:8011 \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "evm_increaseTime",
       "params": ["3600"]
     }'
```

Response:
```
{"jsonrpc":"2.0", "result":"3600", "id":1}
```

### **Requirements:**

1. **Implement the API:**
    - The endpoint should return a populated `U64` of the total time adjustment, in seconds.
    - Ensure the method executes the call reliably and efficiently.
    - Ensure errors are properly returned.

2. **Unit Tests:**
    - Write unit tests to verify the functionality of the `increase_time` method.
    - Ensure coverage for multiple edge-case scenarios.

3. **Documentation:**
    - Add inline Rust documentation (`///` comments) detailing the method's purpose, return values, and any potential edge cases or error scenarios.
    - Update `SUPPORTED_APIS.md` with updated documentation and examples.
    - (Optional) Add request to `test_endpoints.http` for easier manual verification.

### **Task Checklist:**
- [ ] Implement the `increase_time` method.
- [ ] Write unit tests for the `increase_time` method.
- [ ] Add inline documentation for the `evm_increaseTime` endpoint.
- [ ] Update documentation for the `evm_increaseTime` endpoint in `SUPPORTED_APIS.md`.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!
