### ISSUE TITLE
evm_api: Implement `evm_mine` API endpoint

### ISSUE THREAD

**Issue by MexicanAce** [matter-labs/era-test-node#67]
### **Description:**
The `evm_mine` endpoint needs to be implemented. The purpose of this endpoint is to force a single block to be mined.
Will mine an empty block if there are no available transactions to mine. [Ganache docs for reference](https://ganache.dev/#evm_mine).

**NOTE: As of `v0.1.0`, we only support one transaction per block. So the difficulty might increase if this changes in the future.**

```rust
// Interface in the `trait`
#[rpc(name = "evm_mine")]
fn mine(
    &self,
) -> BoxFuture<Result<String>>;

// Actual code in the `impl`
fn mine(
    &self,
) -> BoxFuture<Result<String>> {
    // TODO: Solution here
}
```

#### Expected response
Command returns proper response:
```
curl -X POST http://localhost:8011 \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "evm_mine",
       "params": []
     }'
```

Response:
```
{"jsonrpc":"2.0", "result":"0x0", "id":1}
```

### **Requirements:**

1. **Implement the API:**
    - The endpoint should return `"0x0"` hard-coded string upon success.
    - Ensure the method executes the call reliably and efficiently.
    - Ensure errors are properly returned.

2. **Unit Tests:**
    - Write unit tests to verify the functionality of the `mine` method.
    - Ensure coverage for multiple edge-case scenarios.

3. **Documentation:**
    - Add inline Rust documentation (`///` comments) detailing the method's purpose, return values, and any potential edge cases or error scenarios.
    - Update `SUPPORTED_APIS.md` with updated documentation and examples.
    - (Optional) Add request to `test_endpoints.http` for easier manual verification.

### **Task Checklist:**
- [ ] Implement the `mine` method.
- [ ] Write unit tests for the `mine` method.
- [ ] Add inline documentation for the `evm_mine` endpoint.
- [ ] Update documentation for the `evm_mine` endpoint in `SUPPORTED_APIS.md`.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!

**Comment by MexicanAce** [comment]
Resolved in #116
