### ISSUE TITLE
eth_api: Implement `get_block_by_number` method for `BlockNumber::Earliest` and `BlockNumber::Number(U64)`

### ISSUE THREAD

**Issue by MexicanAce** [matter-labs/era-test-node#71]
### **Description:**
We currently do not handle [`get_block_by_number`](https://github.com/matter-labs/era-test-node/blob/v0.1.0/src/node.rs#L962) method when given `"earliest"` or a specific block number that's not the latest block. This is currently not implemented because if the node is forked, there's no guarantee the block is available in memory.

#### Expected response

Command:
```
# Note: Using mainnet URL for demonstration purposes
curl -X POST https://mainnet.era.zksync.io \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "eth_getBlockByNumber",
       "params": ["earliest", false]
     }'
```
Response:
```
{"jsonrpc":"2.0","result":{"hash":"0xe8e77626586f73b955364c7b4bbf0bb7f7685ebd40e852b164633a4acbd3244c","parentHash":"0x0000000000000000000000000000000000000000000000000000000000000000","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","miner":"0x0000000000000000000000000000000000000000","stateRoot":"0x0000000000000000000000000000000000000000000000000000000000000000","transactionsRoot":"0x0000000000000000000000000000000000000000000000000000000000000000","receiptsRoot":"0x0000000000000000000000000000000000000000000000000000000000000000","number":"0x0","l1BatchNumber":"0x0","gasUsed":"0x0","gasLimit":"0xffffffff","baseFeePerGas":"0x0","extraData":"0x","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","timestamp":"0x0","l1BatchTimestamp":"0x0","difficulty":"0x0","totalDifficulty":"0x0","sealFields":[],"uncles":[],"transactions":[],"size":"0x0","mixHash":"0x0000000000000000000000000000000000000000000000000000000000000000","nonce":"0x0000000000000000"},"id":1}
```

### **Requirements:**

1. **Implement the Method:**
    - The method should no longer error when given `BlockNumber::Earliest` and `BlockNumber::Number(_)` as its argument.
    - Based on the provided value, it should fetch and return the relevant block and add it to Memory.

2. **Unit Tests:**
    - Write unit tests to ensure the `get_block_by_number` method functions correctly.
    - Account for potential edge cases in the tests.
    - Ensure that errors and exceptions are handled appropriately.

3. **Inline Documentation:**
    - Update the `SUPPORTED_APIS.md` document with latest information for API.

### **Task Checklist:**
- [ ] Implement the `get_block_by_number` method for `BlockNumber::Earliest` and `BlockNumber::Number(_)`.
- [ ] Write unit tests for the updated code of `get_block_by_number` method.
- [ ] Update documentation for the `get_block_by_number` method.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!
