### ISSUE TITLE
hardhat_api: Implement `hardhat_impersonateAccount` API endpoint

### ISSUE THREAD

**Issue by MexicanAce** [matter-labs/era-test-node#73]
### **Description:**
The `hardhat_impersonateAccount` endpoint needs to be implemented. The purpose of this endpoint is to impersonate an account given the address. [Hardhat docs for reference](https://hardhat.org/hardhat-network/docs/reference#hardhat_impersonateaccount).

```rust
// Interface in the `trait`
#[rpc(name = "hardhat_impersonateAccount")]
fn impersonate_account(
    &self,
    address: Address,
) -> BoxFuture<Result<bool>>;

// Actual code in the `impl`
fn impersonate_account(
    &self,
    address: Address,
) -> BoxFuture<Result<bool>> {
    // TODO: Solution here
}
```

#### Expected response
Command returns proper response:
```
curl -X POST http://localhost:8011 \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "hardhat_impersonateAccount",
       "params": ["0x36615Cf349d7F6344891B1e7CA7C72883F5dc049"]
     }'
```

Response:
```
{"jsonrpc":"2.0", "result":true, "id":1}
```

### **Requirements:**

1. **Implement the API:**
    - The endpoint should return `true` if successful in impersonating the given address, otherwise `false`.
    - Anytime a request is made to `eth_sendRawTransaction`, it is intercepted and we check if the user is supposed to be impersonated. If it is, then we impersonate and bypass verification for transaction execution.
    - Ensure the method executes the call reliably and efficiently.
    - Ensure errors are properly returned.

2. **Unit Tests:**
    - Write unit tests to verify the functionality of the `impersonate_account` method.
    - Ensure coverage for multiple edge-case scenarios.

3. **Documentation:**
    - Add inline Rust documentation (`///` comments) detailing the method's purpose, return values, and any potential edge cases or error scenarios.
    - Update `SUPPORTED_APIS.md` with updated documentation and examples.
    - (Optional) Add request to `test_endpoints.http` for easier manual verification.

### **Task Checklist:**
- [ ] Implement the `impersonate_account` method.
- [ ] Write unit tests for the `impersonate_account` method.
- [ ] Add inline documentation for the `hardhat_impersonateAccount` endpoint.
- [ ] Update documentation for the `hardhat_impersonateAccount` endpoint in `SUPPORTED_APIS.md`.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!

**Comment by MexicanAce** [comment]
Implemented with #125
