### ISSUE TITLE
hardhat_api: Implement `hardhat_stopImpersonatingAccount` API endpoint

### ISSUE THREAD

**Issue by MexicanAce** [matter-labs/era-test-node#74]
### **Description:**
The `hardhat_stopImpersonatingAccount` endpoint needs to be implemented. The purpose of this endpoint is to stop impersonating an account when `hardhat_impersonateAccount` has been called already. [Hardhat docs for reference](https://hardhat.org/hardhat-network/docs/reference#hardhat_stopimpersonatingaccount).

**ℹ️ The `address` parameter doesn't have to be used as we can only support impersonation of up to 1 account at a time**

**:warning: NOTE : This is dependent on https://github.com/matter-labs/era-test-node/issues/73 being completed first!**

```rust
// Interface in the `trait`
#[rpc(name = "hardhat_stopImpersonatingAccount")]
fn stop_impersonate_account(
    &self,
    address: Address,
) -> BoxFuture<Result<bool>>;

// Actual code in the `impl`
fn stop_impersonate_account(
    &self,
    address_: Address,
) -> BoxFuture<Result<bool>> {
    // TODO: Solution here
}
```

#### Expected response
Command returns proper response:
```
curl -X POST http://localhost:8011 \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "hardhat_stopImpersonatingAccount",
       "params": ["0x36615Cf349d7F6344891B1e7CA7C72883F5dc049"]
     }'
```

Response:
```
{"jsonrpc":"2.0", "result":true, "id":1}
```

### **Requirements:**

1. **Implement the API:**
    - The endpoint should return `true` if successfully no longer impersonating account, otherwise `false`.
    - Ensure the method executes the call reliably and efficiently.
    - Ensure errors are properly returned.

2. **Unit Tests:**
    - Write unit tests to verify the functionality of the `stop_impersonate_account` method.
    - Ensure coverage for multiple edge-case scenarios.

3. **Documentation:**
    - Add inline Rust documentation (`///` comments) detailing the method's purpose, return values, and any potential edge cases or error scenarios.
    - Update `SUPPORTED_APIS.md` with updated documentation and examples.
    - (Optional) Add request to `test_endpoints.http` for easier manual verification.

### **Task Checklist:**
- [ ] Implement the `stop_impersonate_account` method.
- [ ] Write unit tests for the `stop_impersonate_account` method.
- [ ] Add inline documentation for the `hardhat_stopImpersonatingAccount` endpoint.
- [ ] Update documentation for the `hardhat_stopImpersonatingAccount` endpoint in `SUPPORTED_APIS.md`.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!

**Comment by MexicanAce** [comment]
Implemented with #125
