### ISSUE TITLE
hardhat_api: Implement `hardhat_mine` API endpoint

### ISSUE THREAD

**Issue by MexicanAce** [matter-labs/era-test-node#75]
### **Description:**
The `hardhat_mine` endpoint needs to be implemented. The purpose of this endpoint is to mine any number of blocks at once, in constant time. [Hardhat docs for reference](https://hardhat.org/hardhat-network/docs/reference#hardhat_mine).

```rust
// Interface in the `trait`
#[rpc(name = "hardhat_mine")]
fn mine(
    &self,
    blocks: U64, // Number of Blocks to mine (default is 1)
    interval: Option<U64>, //  Time interval of block timestamp (default is 1)
) -> BoxFuture<Result<bool>>;

// Actual code in the `impl`
fn mine(
    &self,
    blocks: U64,
    interval: Option<U64>,
) -> BoxFuture<Result<bool>> {
    // TODO: Solution here
}
```

#### Expected response
Command returns proper response:
```
curl -X POST http://localhost:8011 \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "hardhat_mine",
       "params": [100]
     }'
```

Response:
```
{"jsonrpc":"2.0", "result":true, "id":1}
```

### **Requirements:**

1. **Implement the API:**
    - The endpoint should return `true` if successful in mining the requested number of blocks, otherwise `false`.
    - Ensure the method executes the call reliably and efficiently.
    - Ensure errors are properly returned.

2. **Unit Tests:**
    - Write unit tests to verify the functionality of the `mine` method.
    - Ensure coverage for multiple edge-case scenarios.

3. **Documentation:**
    - Add inline Rust documentation (`///` comments) detailing the method's purpose, return values, and any potential edge cases or error scenarios.
    - Update `SUPPORTED_APIS.md` with updated documentation and examples.
    - (Optional) Add request to `test_endpoints.http` for easier manual verification.

### **Task Checklist:**
- [ ] Implement the `mine` method.
- [ ] Write unit tests for the `mine` method.
- [ ] Add inline documentation for the `hardhat_mine` endpoint.
- [ ] Update documentation for the `hardhat_mine` endpoint in `SUPPORTED_APIS.md`.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!

**Comment by MexicanAce** [comment]
Resolved in #116
