### ISSUE TITLE
hardhat_api: Implement `hardhat_setBalance` API endpoint

### ISSUE THREAD

**Issue by MexicanAce** [matter-labs/era-test-node#76]
### **Description:**
The `hardhat_setBalance` endpoint needs to be implemented. The purpose of this endpoint is to modify the balance of an account. [Hardhat docs for reference](https://hardhat.org/hardhat-network/docs/reference#hardhat_setbalance).

```rust
// Interface in the `trait`
#[rpc(name = "hardhat_setBalance")]
fn set_balance(
    &self,
    address: Address, // The address whose balance will be edited
    balance: U256, // The new balance to set for the given address, in wei
) -> BoxFuture<Result<bool>>;

// Actual code in the `impl`
fn set_balance(
    &self,
    address: Address,
    balance: U256,
) -> BoxFuture<Result<bool>> {
    // TODO: Solution here
}
```

#### Expected response
Command returns proper response:
```
curl -X POST http://localhost:8011 \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "hardhat_setBalance",
       "params": ["0x36615Cf349d7F6344891B1e7CA7C72883F5dc049", "0x1000"]
     }'
```

Response:
```
{"jsonrpc":"2.0", "result":true, "id":1}
```

### **Requirements:**

1. **Implement the API:**
    - The endpoint should return `true` if successful in updating the balance of the account, otherwise `false`.
    - Ensure the method executes the call reliably and efficiently.
    - Ensure errors are properly returned.

2. **Unit Tests:**
    - Write unit tests to verify the functionality of the `set_balance` method.
    - Ensure coverage for multiple edge-case scenarios.

3. **Documentation:**
    - Add inline Rust documentation (`///` comments) detailing the method's purpose, return values, and any potential edge cases or error scenarios.
    - Update `SUPPORTED_APIS.md` with updated documentation and examples.
    - (Optional) Add request to `test_endpoints.http` for easier manual verification.

### **Task Checklist:**
- [ ] Implement the `set_balance` method.
- [ ] Write unit tests for the `set_balance` method.
- [ ] Add inline documentation for the `hardhat_setBalance` endpoint.
- [ ] Update documentation for the `hardhat_setBalance` endpoint in `SUPPORTED_APIS.md`.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!
