### ISSUE TITLE
hardhat_api: Implement `hardhat_setNonce` API endpoint

### ISSUE THREAD

**Issue by MexicanAce** [matter-labs/era-test-node#77]
### **Description:**
The `hardhat_setNonce` endpoint needs to be implemented. The purpose of this endpoint is to modify the nonce of an account. [Hardhat docs for reference](https://hardhat.org/hardhat-network/docs/reference#hardhat_setnonce).

**ℹ️ You can only use this method to increase the nonce of an account; you can't set a lower value than the account's current nonce.**

Throws an `InvalidInputError` if nonce is smaller than the current one. The reason for this restriction is to avoid collisions when deploying contracts using the same nonce more than once.

```rust
// Interface in the `trait`
#[rpc(name = "hardhat_setNonce")]
fn set_nonce(
    &self,
    address: Address, // The address whose nonce is to be changed
    nonce: H64, // The new nonce
) -> BoxFuture<Result<bool>>;

// Actual code in the `impl`
fn set_nonce(
    &self,
    address: Address,
    nonce: H64,
) -> BoxFuture<Result<bool>> {
    // TODO: Solution here
}
```

#### Expected response
Command returns proper response:
```
curl -X POST http://localhost:8011 \
     -H "Content-Type: application/json" \
     --data '{
       "jsonrpc": "2.0",
       "id": 1,
       "method": "hardhat_setNonce",
       "params": ["0x36615Cf349d7F6344891B1e7CA7C72883F5dc049", "0x21"]
     }'
```

Response:
```
{"jsonrpc":"2.0", "result":true, "id":1}
```

### **Requirements:**

1. **Implement the API:**
    - The endpoint should return `true` if successful in updating the balance of the account, otherwise `false`.
    - Ensure the method executes the call reliably and efficiently.
    - Ensure errors are properly returned.

2. **Unit Tests:**
    - Write unit tests to verify the functionality of the `set_nonce` method.
    - Ensure coverage for multiple edge-case scenarios.

3. **Documentation:**
    - Add inline Rust documentation (`///` comments) detailing the method's purpose, return values, and any potential edge cases or error scenarios.
    - Update `SUPPORTED_APIS.md` with updated documentation and examples.
    - (Optional) Add request to `test_endpoints.http` for easier manual verification.

### **Task Checklist:**
- [ ] Implement the `set_nonce` method.
- [ ] Write unit tests for the `set_nonce` method.
- [ ] Add inline documentation for the `hardhat_setNonce` endpoint.
- [ ] Update documentation for the `hardhat_setNonce` endpoint in `SUPPORTED_APIS.md`.

### **Additional Notes:**
If you're an external contributor looking to take on this issue, please comment below to let us know you're working on it. If you need further clarification on the requirements or need assistance with anything related to the implementation, feel free to ask!
